# Generated by Django 5.0.4 on 2026-09-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='avatars/%Y/%m/'),
        ),
    ]
