# Generated by Django 5.0.4 on 2026-09-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='academic_level',
            field=models.CharField(blank=True, choices=[('100', 'Level 100 (Freshmen)'), ('200', 'Level 200 (Sophomores)'), ('300', 'Level 300 (Juniors)'), ('400', 'Level 400 (Seniors)'), ('postgraduate', 'Postgraduate')], default='100', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('staff', 'Staff'), ('finance', 'Finance Officer'), ('admin', 'Admin')], db_index=True, default='student', max_length=20),
        ),
    ]
