# Generated by Django 5.0.4 on 2026-09-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_academic_level_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admission_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='class_name',
            field=models.CharField(blank=True, default='100', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='moh_pin',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='program',
            field=models.CharField(blank=True, choices=[('nursing', 'Nursing'), ('midwifery', 'Midwifery')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='serial_number',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='IDSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(db_index=True, max_length=30)),
                ('class_name', models.CharField(blank=True, default='', max_length=50)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'id_sequences',
                'unique_together': {('program', 'class_name', 'year')},
            },
        ),
    ]
