# Generated by Django 5.0.4 on 2026-09-20 16:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0005_userprofile_birth_place_userprofile_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProgressionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('promotion', 'Promotion'), ('demotion', 'Demotion'), ('withdrawal', 'Withdrawal'), ('reinstatement', 'Reinstatement'), ('graduation', 'Graduation'), ('status_change', 'Status Change'), ('soft_delete', 'Soft Delete'), ('restore', 'Restore')], db_index=True, max_length=30)),
                ('from_level', models.CharField(blank=True, max_length=50)),
                ('to_level', models.CharField(blank=True, max_length=50)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(blank=True, max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('academic_year', models.CharField(blank=True, max_length=30)),
                ('semester', models.CharField(blank=True, max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'academic_progression_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='academic_status',
            field=models.CharField(choices=[('active', 'Active'), ('probation', 'Academic Probation'), ('repeating', 'Repeating'), ('withdrawn', 'Withdrawn'), ('suspended', 'Suspended'), ('graduated', 'Graduated'), ('deleted', 'Deleted / Archived')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='withdrawal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='withdrawal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'academic_status'], name='users_role_08e88f_idx'),
        ),
        migrations.AddField(
            model_name='academicprogressionlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_progressions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicprogressionlog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='academicprogressionlog',
            index=models.Index(fields=['student', 'created_at'], name='academic_pr_student_e865d9_idx'),
        ),
        migrations.AddIndex(
            model_name='academicprogressionlog',
            index=models.Index(fields=['action', 'created_at'], name='academic_pr_action_f436c1_idx'),
        ),
    ]
