# Generated by Django 5.0.4 on 2026-09-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_academicprogressionlog_user_academic_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_functions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('academic_officer', 'Academic Officer'), ('head_of_department', 'Head of Department'), ('finance', 'Finance Officer'), ('lecturer', 'Lecturer'), ('student', 'Student'), ('admin', 'Admin (Legacy)'), ('staff', 'Staff (Legacy)'), ('instructor', 'Instructor (Legacy)')], db_index=True, default='student', max_length=30),
        ),
    ]
