# Generated by Django 5.0.4 on 2026-09-23 00:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_assigned_functions_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor_email', models.CharField(blank=True, db_index=True, max_length=255)),
                ('actor_role', models.CharField(blank=True, db_index=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('action_category', models.CharField(choices=[('auth', 'Authentication & Session'), ('user_management', 'User & Access Management'), ('academics', 'Academics & Grading'), ('financials', 'Financials & Billing'), ('security', 'Security & System Shielding'), ('system', 'System & Data Maintenance')], db_index=True, default='system', max_length=40)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('warning', 'Warning')], db_index=True, default='success', max_length=20)),
                ('target_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('target_repr', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'action_category'], name='audit_logs_timesta_5ecc05_idx'), models.Index(fields=['actor_email', 'timestamp'], name='audit_logs_actor_e_53daca_idx'), models.Index(fields=['action', 'status'], name='audit_logs_action_d96607_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_logs_target__9fc8de_idx')],
            },
        ),
    ]
