# Generated by Django 5.0.4 on 2026-09-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('academic_officer', 'Academic Officer'), ('head_of_department', 'Head of Department'), ('finance', 'Finance Officer'), ('lecturer', 'Lecturer'), ('student', 'Student'), ('admin', 'Admin (Legacy)'), ('staff', 'Staff (Legacy)'), ('instructor', 'Instructor (Legacy)'), ('super-admin', 'Super Admin (Alias)'), ('academic-officer', 'Academic Officer (Alias)'), ('departmental-head', 'Departmental Head (Alias)'), ('head-of-department', 'Head of Department (Alias)'), ('finance-officer', 'Finance Officer (Alias)'), ('finance_officer', 'Finance Officer (Alias)')], db_index=True, default='student', max_length=30),
        ),
    ]
