# Generated by Django 5.0.4 on 2026-09-03 10:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterFeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(default='First Semester 2024/2025', max_length=60, unique=True)),
                ('academic_fee', models.DecimalField(decimal_places=2, default=Decimal('3850.00'), max_digits=10)),
                ('ict_library_fee', models.DecimalField(decimal_places=2, default=Decimal('350.00'), max_digits=10)),
                ('src_dues', models.DecimalField(decimal_places=2, default=Decimal('180.00'), max_digits=10)),
                ('examination_fee', models.DecimalField(decimal_places=2, default=Decimal('220.00'), max_digits=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Semester Fee Structure',
                'verbose_name_plural': 'Semester Fee Structures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='Outstanding semester fee arrears exceeding GH₵ 500.00', max_length=255)),
                ('amount_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_holds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAccountStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(default='First Semester 2024/2025', max_length=60)),
                ('academic_fee', models.DecimalField(decimal_places=2, default=Decimal('3850.00'), max_digits=10)),
                ('ict_library_fee', models.DecimalField(decimal_places=2, default=Decimal('350.00'), max_digits=10)),
                ('src_dues', models.DecimalField(decimal_places=2, default=Decimal('180.00'), max_digits=10)),
                ('examination_fee', models.DecimalField(decimal_places=2, default=Decimal('220.00'), max_digits=10)),
                ('bursary_aid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_billed', models.DecimalField(decimal_places=2, default=Decimal('4600.00'), max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('4600.00'), max_digits=10)),
                ('currency', models.CharField(default='GHS', max_length=10)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Part Payment'), ('paid', 'Paid in Full'), ('overdue', 'Overdue')], default='unpaid', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_statements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GHS', max_length=10)),
                ('channel', models.CharField(choices=[('momo', 'Mobile Money'), ('bank_api', 'Automated Bank Collect'), ('bank_manual', 'Bank Deposit Slip'), ('bursary', 'Scholarship / Bursary')], default='momo', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=60)),
                ('phone_or_account', models.CharField(blank=True, max_length=60)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('receipt_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending_verification', 'Pending Verification'), ('failed', 'Failed')], default='completed', max_length=25)),
                ('slip_image', models.ImageField(blank=True, null=True, upload_to='bank_slips/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financials.studentaccountstatement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
