# Generated by Django 5.0.4 on 2026-09-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semesterfeestructure',
            options={'ordering': ['academic_level', '-created_at'], 'verbose_name': 'Semester Fee Structure', 'verbose_name_plural': 'Semester Fee Structures'},
        ),
        migrations.AddField(
            model_name='semesterfeestructure',
            name='academic_level',
            field=models.CharField(choices=[('100', 'Level 100 (Freshmen)'), ('200', 'Level 200 (Sophomores)'), ('300', 'Level 300 (Juniors)'), ('400', 'Level 400 (Seniors / Final Year)'), ('postgraduate', 'Postgraduate / Masters'), ('all', 'All Levels (Standard Tariff)')], db_index=True, default='100', max_length=20),
        ),
        migrations.AddField(
            model_name='semesterfeestructure',
            name='level_title',
            field=models.CharField(blank=True, default='Level 100 (Freshmen)', max_length=100),
        ),
        migrations.AddField(
            model_name='studentaccountstatement',
            name='academic_level',
            field=models.CharField(blank=True, default='100', max_length=20),
        ),
        migrations.AlterField(
            model_name='semesterfeestructure',
            name='semester',
            field=models.CharField(default='First Semester 2024/2025', max_length=60),
        ),
        migrations.AlterUniqueTogether(
            name='semesterfeestructure',
            unique_together={('semester', 'academic_level')},
        ),
    ]
