# Generated by Django 5.0.4 on 2026-07-10 02:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('feedback', models.TextField(blank=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='GradeBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('rejected', 'Rejected'), ('approved', 'Approved'), ('published', 'Published')], db_index=True, default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('submission_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'grade_batches',
            },
        ),
        migrations.CreateModel(
            name='SemesterRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semester', models.CharField(db_index=True, max_length=20)),
                ('semester_label', models.CharField(max_length=30)),
                ('semester_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('semester_credits_attempted', models.PositiveSmallIntegerField(default=0)),
                ('semester_credits_earned', models.PositiveSmallIntegerField(default=0)),
                ('semester_quality_points', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cumulative_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cumulative_credits_attempted', models.PositiveSmallIntegerField(default=0)),
                ('cumulative_credits_earned', models.PositiveSmallIntegerField(default=0)),
                ('cumulative_quality_points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn')], default='in_progress', max_length=20)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'semester_records',
                'ordering': ['-semester'],
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('semester', models.CharField(db_index=True, max_length=20)),
                ('semester_label', models.CharField(max_length=30)),
                ('final_grade', models.CharField(blank=True, max_length=5)),
                ('grade_points', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('credits_attempted', models.PositiveSmallIntegerField(default=0)),
                ('credits_earned', models.PositiveSmallIntegerField(default=0)),
                ('quality_points', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'transcripts',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('assignment_type', models.CharField(choices=[('homework', 'Homework'), ('midterm', 'Midterm Exam'), ('final', 'Final Exam'), ('quiz', 'Quiz'), ('project', 'Project'), ('lab', 'Lab'), ('attendance', 'Attendance')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, default=0, help_text='Percentage weight toward final course grade', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('due_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course')),
            ],
            options={
                'db_table': 'assignments',
            },
        ),
    ]
