# Generated by Django 5.0.4 on 2026-07-10 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_initial'),
        ('grades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grade',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grades.assignment'),
        ),
        migrations.AddField(
            model_name='grade',
            name='graded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradebatch',
            name='assignment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade_batch', to='grades.assignment'),
        ),
        migrations.AddField(
            model_name='gradebatch',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradebatch',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='semesterrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transcript',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='courses.course'),
        ),
        migrations.AddField(
            model_name='transcript',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['course', 'due_date'], name='assignments_course__727d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'is_published'], name='grades_student_acc642_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'assignment')},
        ),
        migrations.AddIndex(
            model_name='gradebatch',
            index=models.Index(fields=['status'], name='grade_batch_status_ebaddb_idx'),
        ),
        migrations.AddIndex(
            model_name='semesterrecord',
            index=models.Index(fields=['student', 'semester'], name='semester_re_student_e65529_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='semesterrecord',
            unique_together={('student', 'semester')},
        ),
        migrations.AddIndex(
            model_name='transcript',
            index=models.Index(fields=['student', 'semester'], name='transcripts_student_a67f49_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transcript',
            unique_together={('student', 'course', 'semester')},
        ),
    ]
