# Generated by Django 5.0.4 on 2026-09-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0003_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='score_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
