# Generated by Django 5.0.4 on 2026-09-29 01:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('files', '0002_initial'),
        ('grades', '0005_submission_feedback_submission_graded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeAppeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('suggested_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('reason', models.TextField(help_text='Detailed justification for the grade appeal or correction')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('hod_approved', 'HOD Endorsed'), ('approved', 'Approved & Corrected'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('lecturer_comment', models.TextField(blank=True)),
                ('hod_comment', models.TextField(blank=True)),
                ('decision_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_appeals', to='courses.course')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='grades.grade')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_grade_appeals', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_appeals', to=settings.AUTH_USER_MODEL)),
                ('supporting_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_appeals', to='files.uploadedfile')),
            ],
            options={
                'db_table': 'grade_appeals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='grade_appea_student_9e1f62_idx'), models.Index(fields=['course', 'status'], name='grade_appea_course__349c93_idx'), models.Index(fields=['status', 'created_at'], name='grade_appea_status_cc5021_idx')],
            },
        ),
    ]
