# Generated by Django 5.0.4 on 2026-07-10 02:05

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notif_type', models.CharField(choices=[('grade_posted', 'Grade Posted'), ('enrollment_confirmed', 'Enrollment Confirmed'), ('assignment_due', 'Assignment Due'), ('grade_batch_approved', 'Grade Batch Approved'), ('grade_batch_rejected', 'Grade Batch Rejected'), ('grade_batch_published', 'Grade Batch Published'), ('grade_review_requested', 'Grade Review Requested'), ('announcement', 'Announcement'), ('system', 'System')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
