# Generated by Django 5.0.4 on 2026-09-23 00:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_phone', models.CharField(db_index=True, max_length=32)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=255)),
                ('message_body', models.TextField()),
                ('sender_id', models.CharField(default='ASDAM', max_length=30)),
                ('purpose', models.CharField(blank=True, db_index=True, default='general', max_length=64)),
                ('provider', models.CharField(default='Arkesel', max_length=32)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted / Queued'), ('DELIVERED', 'Delivered'), ('PENDING_APPROVAL', 'Pending Approval'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected'), ('SIMULATED', 'Simulated')], db_index=True, default='PENDING', max_length=30)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('retries_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sms_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='sms_logs_status_25f072_idx'), models.Index(fields=['recipient_phone', 'created_at'], name='sms_logs_recipie_9bdec8_idx'), models.Index(fields=['provider_message_id'], name='sms_logs_provide_4b4157_idx')],
            },
        ),
    ]
